# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dencomm
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dencomm-serverless-template
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dencomm-serverless-template

provider:
  # The name of the AWS provider
  name: aws
  # The AWS region
  region: ap-northeast-2
  # AWS Lambda 실행 환경
  runtime: nodejs20.x
  # AWS Lambda 런타임 매니지먼트 - default : auto
  runtimeManagement: auto
  # AWS Lambda 함수 실행 메모리
  memorySize: 128
  # default timeout
  timeout: 20
  #default stage
  stage: ${env:stage, 'dev'}
  # environment variables -> AWS Lambda 함수에 전달되는 환경 변수
  environment:
    APP_STAGE: ${env:stage, self:provider.stage}
  # VPC 설정 - https://www.serverless.com/framework/docs/providers/aws/guide/functions#vpc-configuration
  #vpc:
    #  securityGroupIds
functions:
  hello:
    handler: handler.hello
  testError:
    handler: handler.testError

