# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dencomm
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dencomm-serverless-example
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dencomm-serverless-example

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
